repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff format
        entry: env
        args: [UV_NO_BINARY_PACKAGE=multi-swe-bench, uv, run, ruff, format]
        language: system
        types: [python]
        pass_filenames: true
        always_run: false
      - id: ruff-check
        name: Ruff lint
        entry: env
        args:
          [
            UV_NO_BINARY_PACKAGE=multi-swe-bench,
            uv,
            run,
            ruff,
            check,
            --fix,
            --exit-non-zero-on-fix,
          ]
        language: system
        types: [python]
        pass_filenames: true
        always_run: false
      - id: pycodestyle
        name: PEP8 style check (pycodestyle)
        entry: env
        args:
          [
            UV_NO_BINARY_PACKAGE=multi-swe-bench,
            uv,
            run,
            pycodestyle,
            --max-line-length=88,
            "--ignore=E203,E501,W503,E704",
          ]
        language: system
        types: [python]
        pass_filenames: true
        always_run: false
      - id: pyright
        name: Type check with Pyright (strict)
        entry: env
        args: [UV_NO_BINARY_PACKAGE=multi-swe-bench, uv, run, pyright]
        language: system
        types: [python]
        pass_filenames: true
        always_run: false
